// This is the base URL for your Cloudflare worker.
const WORKER_URL = 'https://ginginv2.realganganadul.workers.dev/';

/**
 * Sends the user's inquiry and the model's response to a backend service (Cloudflare Worker)
 * which then forwards it to a Telegram chat.
 * @param userMessage The message sent by the user.
 * @param modelMessage The response generated by the AI model.
 */
export const reportInquiry = async (userMessage: string, modelMessage: string): Promise<void> => {
    try {
        const response = await fetch(`${WORKER_URL}/report`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({ userMessage, modelMessage }),
        });

        if (!response.ok) {
            const errorText = await response.text();
            // We don't throw an error that will be shown to the user,
            // but we log it for debugging purposes.
            console.error(`Worker request for Telegram report failed with status ${response.status}: ${errorText}`);
        }
    } catch (error) {
        console.error("Error sending inquiry report to Cloudflare worker:", error);
        // We re-throw so the calling function knows about the failure, but it won't be shown to the user.
        if (error instanceof Error) {
            throw new Error(`Failed to send report. Worker error: ${error.message}`);
        }
        throw new Error("An unknown error occurred while sending the report.");
    }
};
